[package]
name = "shida_configuration_factory"
version = "0.1.0"
edition = "2021"

[dependencies]
shida = { path = "../shida" }
shida_data_directory = { path = "../shida_data_directory" }
shida_repl = { path = "../shida_repl" }
